language: elixir

elixir:
  - 1.8
otp_release:
  - 21.0

sudo: false

before_script:
  - mix do deps.get, deps.compile
  - mix do ecto.create, ecto.migrate

script:
  - mix test --cover

env:
  - MIX_ENV=test

addons:
  postgresql: '9.4'

cache:
  directories:
    - _build
    - deps
