language: elixir

elixir:
  - 1.3
otp_release:
  - 19.1

sudo: false

script: "MIX_ENV=test mix do deps.get, deps.compile, ecto.migrate, test --cover"

addons:
  postgresql: '9.4'

cache:
  directories:
    - _build
    - deps
